### PR TITLE
ensured .cancel() only invoked when in prototype chain

### LINKED ISSUE #118: TypeError when `cache.match()` returns 304 response due to matching `If-None-Match` header
See more detail in my comment here: https://github.com/cloudflare/kv-asset-handler/pull/115/files#r445871787

tl;dr: now that we're including ETag headers on cached responses, and If-None-Match headers on requests, calls to `cache.match(request)` may return `304 Not Modified` responses which have no body. More detail about how this happens is in the [Cache API docs for the `match` method](https://developers.cloudflare.com/workers/reference/apis/cache/).

This (a) throws a `TypeError` on matches when accessing `request.body.cancel` in the current implementation, and (b) means we should probably revisit the `shouldRevalidate` logic.

You can repro by:
1. Set up a new Gatsby project
1. Follow [the docs to deploy it via Workers Sites](https://developers.cloudflare.com/workers/sites/start-from-existing/)
1. Check out the tip of master of `kv-asset-handler` in another directory
1. Run `npm link` there
1. `cd ~/my-gatsby-project && npm link @cloudflare/kv-asset-handler` to replace the npm package with your local tip of master
1. `wrangler publish` again
1. Smash reload a bunch of times and observe 500s on every 2nd request, when the request has `If-None-Match` headers and thus triggers a cache match

The simple solution is to defend against `request.body` being null in the `shouldRevalidate` logic, but I'm not sure if we need to make further updates to that logic for the sake of correctness. We'll need to address this before releasing 0.0.11.

FYI @shagamemnon @harrishancock @SukkaW

### PR DESCRIPTION
**Pull request by shagamemnon**
Fixes #118 per thread #115

### CODE REVIEW

**Comment by shagamemnon** [comment]
cc: @ispivey @SukkaW @harrishancock

**Comment by shagamemnon** [comment]
Thanks @SukkaW  :)

With respect to using `typeof` as a failsafe - I'm not sure I understand the need to evaluate the object type in this scenario. `.cancel()` is a method called on a `ReadableStream`. `response.body` IS a `ReadableStream` by definition. It delegates to that prototype and so it has the `.cancel()` method. We aren't going to check if other standard JS methods like `Array.prototype.every()` or `Array.prototype.map()` are functions, so I'm struggling to understand why we'd apply that test to `.cancel()`. Can you explain to me?

**Comment by SukkaW** [comment]
> Can you explain to me?

@shagamemnon We should always add a failsafe in case prototype being polluted or override.  For instance, test cases and the `global` we mocked might not have the exact behavior as Cloudflare Workers environment (As you can see, in Cloudflare Workers environment the `response.body` could even be null).

**Comment by ispivey** [comment]
`Request` implements the `Body` mixin and thus `body` property which is either null or a `ReadableStream`, per the [Fetch API spec](https://fetch.spec.whatwg.org/#response-class) – having a null body is a valid implementation of the spec that this code should handle. 

However, a `ReadableStream` must implement a `cancel` method, per the [Streams spec](https://streams.spec.whatwg.org/#rs-prototype). If the `cancel` method does not exist or is not a function, then whatever is providing the `Response` and its `body` should update that implementation to conform – for example, the mocks.

@SukkaW , I do get the argument that it's always possible for a prototype to be polluted or overridden, but that's the case with literally every part of environment-provided APIs like this, and we don't proactively validate that every method or property is provided as we expect. I think as authors of libraries we should be able to assume that environments comply with the spec, except in cases where we know that they don't and that causes specific issues we need to work around.

In the interest of getting a release tested and out the door, and because of the spec-compliance angle described above, I'm happy to merge this as-is.

**Pull request merged**
