### PR TITLE
package lock

### PR DESCRIPTION
**Pull request by victoriabernard92**

### CODE REVIEW

**Comment by ispivey** [comment]
@victoriabernard92 I had the same Q as @EverlastingBugstopper ! I saw the 0.10.0 PR with the changelog updates was #86 – what's this one?

**Comment by victoriabernard92** [comment]
I forgot to commit the package-lock (good thing we're making a release checklist 😄 ) I don't think we should include changelog since it's just bumping the package in the package lock. Check out the diff and let me know if I did that wrong please @EverlastingBugstopper

**Comment by EverlastingBugstopper** [comment]
@victoriabernard92 - did we already merge the changelog? I'm assuming there's more to this release than just rolling deps.

If we've already merged the changelog that's fine, but generally for release PRs we do everything on the checklist in a single PR.

**Comment by victoriabernard92** [comment]
Sorry for not making this clear in the description. This was an accident on my part I meant to add changelog in release PR @EverlastingBugstopper

**Pull request merged**
