### PR TITLE
Support ES6 Module Syntax 

### PR DESCRIPTION
**Pull request by DrewRidley**
Here I introduce a possible solution for handling the retrieval of assets from the KV when using the module syntax in your workers. You can see in my PR that instead of ``FetchEvent``, the method takes in ``Request`` and ``Context``. Both objects are provided to the workers and can easily be passed into this method.

### CODE REVIEW

**Comment by Cherry** [comment]
Thanks so much for submitting this PR!

I'm not sure that adding a separate method is the best way to go about doing this though, and adds two methods with very similar code, adding some additional maintenance any time we want to make changes.

I'd suggest that we extend `getAssetFromKV` to detect what's being passed into it via `instanceof`, perhaps passing in `env` as an optional third parameter. Alternatively, splitting up the code in `getAssetFromKV` so these 2 separate functions can share almost identical logic could be another solution.

I'd love to hear from some users that have worked with ESM workers to get their thoughts on the kind of interface they'd like to see, or think would be most ideal here.

@PeterCxy
@frandlox
@signalnerve 
@ttraenkler 
@evanderkoogh
@lemonmade
@tranzium

**Comment by DrewRidley** [comment]
I am happy rewriting this to take advantage of ``instanceOf()`` and that might seem advantageous. I personally disliked the idea of having multiple exported functions with very similar prototypes. Its a shame that JS doesn't support overloads.

Regardless, I will see if I can create another prototype that uses ``instanceOf()`` and still exports one method for the sake of API consistency.

**Comment by DrewRidley** [comment]
I just updated the reference implementation to use TS overloads. In theory this will work, but the TS compiler compiled despite the code technically not being valid.

``arg2`` in the reference implementation may be null, but the TS compiler didnt require me to write ``undefined`` or add a nullable ``?`` in front of the argument. I will be using this implementation on my worker in a few minutes to test, but as far as I can tell this will work correctly for both old and new projects.

**Comment by DrewRidley** [comment]
Given all the failed tests that just appeared, I think its safe to say that I need a bit more time to flesh out this PR. 
Apologies for the delays.

**Comment by DrewRidley** [comment]
Alright, sorry for the delays everyone. It now passes all tests and should work.

**Comment by DrewRidley** [comment]
Before this PR is merged we should probably wait and see how the ``CONTENT_MANIFEST`` will look on module workers. It appears that when this manifest is re-introduced under the modules, it will have a different syntax and thus, will require this PR to look a bit different.

I'll keep my eye on that issue and when progress is made I will update this PR accordingly.
https://github.com/cloudflare/wrangler/issues/1938

**Comment by DrewRidley** [comment]
Unfortunately theres not really much I can do because of the way cloudflare workers work. Its quite simply impossible to have one ``kv-asset-handler`` for both syntaxes. ``kv-asset-handler`` has a deep integration with exported constants like ``ASSET_NAMESPACE`` and ``ASSET_MANIFEST``. While I did manage to get wrangler to upload the content manifest, its of little use because I need to import it. Using dynamic imports works, but it requires typescript to build the project with a module syntax, which would not be compliant for service workers. As a result, the best approach needs to be an alternative ESM module, because as it stands I see no possible way to integrate support for both syntaxes in one library.

**Comment by revmischa** [comment]
Excited for this to land! It's sort of a blocker for me

**Comment by revmischa** [comment]
I tested this out with https://github.com/cloudflare/wrangler/pull/1973/files and my STATIC_MANIFEST appears to be empty as far as I can tell

**Comment by signalnerve** [comment]
apologies for the delay on review, everyone! @Cherry how do you feel about this? if anyone is testing this on their projects, logs/output appreciated in this issue so we can get a sense of how this is working 👍

**Comment by Cherry** [comment]
> apologies for the delay on review, everyone! @Cherry how do you feel about this? if anyone is testing this on their projects, logs/output appreciated in this issue so we can get a sense of how this is working 👍

@DrewRidley can probably speak more on this, but I think the consensus was that this doesn't really work as a combined function, and would best be served as a separate method or module (?). Perhaps we'd dual-publish and include a `/esm` import or something for this?

I haven't tested it myself honestly (we still haven't dived into ESM workers yet), but it would definitely be reliant on https://github.com/cloudflare/wrangler/pull/1973, and anything else that needs to change in Wrangler first. Drew can probably talk a little more on that.

My understanding too was that that eventually ESM workers would be the _default_ workers format, so it may even make sense for us to simply release a breaking change (`1.x` maybe), with this functionality as the default once that does happen. 🤔

**Comment by lkj4** [comment]
There are a handful of issues open re getting this PR resolved and eventually getting CF DO on SvelteKit working (this is at least my motivation).

Since summer, these issues are kind of stalling and even if DOs are still in beta, your users need to have these issues resolved just to get basic DO functionality working on popular platforms and not just for some edge (pun) use cases. Beyond that, it would be great to have breaking changes asap, so we are not building on deprecating APIs.

Before I comment on all those issues/PRs, I just do it just here:

When will we see further progress, what/who is the current bottle neck on CF's side? Did CF de prioritize DOs? Can Drew do anything? /cc xortive

Looking fwd to some merges 🙂

**Comment by Cherry** [comment]
My understanding is that the biggest holdup here is with Wrangler support:

- https://github.com/cloudflare/wrangler/issues/1938
- https://github.com/cloudflare/wrangler/pull/1973
- https://github.com/cloudflare/wrangler/pull/2114

Some folks have managed to hack around it and get things to work, such as https://github.com/g45t345rt/cf-ssr-template, but the experience is not ideal right now.

Once support is resolved upstream, this PR can be updated and merged, and things should work!

**Comment by Cherry** [comment]
Now that https://github.com/cloudflare/kv-asset-handler/pull/261 has landed here, and https://github.com/cloudflare/wrangler/pull/2126 in wrangler, support for ES Modules is coming in `0.2.0`. 🎉

Thanks so much for your effort on this PR @DrewRidley!

**Pull request closed without merging**
