### PR TITLE
revert non-ascii support

### PR DESCRIPTION
**Pull request by EverlastingBugstopper**
unfortunately, @harrishancock let me know that #100 introduced a breaking change. 

this pr reverts those changes and adds test cases for what it had broken. i still think it's valuable to allow non-ascii characters in URLs, but we'll have to do it another way.

cc @SukkaW

### CODE REVIEW

**Comment by kentonv** [comment]
@harrishancock @EverlastingBugstopper Keep in mind that the threshold for an acceptable breaking change in a library is very different from the runtime. A breaking change in the runtime will break people at a random time they have no control over. A breaking change in a library will break them only when they update their dependency versions and re-deploy. People _should_ do some testing after updating dependencies, but even if they don't, at least the breakage hits when they are online and actively changing things, and more likely to be able to take care of it.

I'm not necessarily saying that this breaking change is acceptable, just wanted to make sure the absolutely-no-changes culture from the runtime doesn't bleed over into other components where it's detrimental.

I guess the thought here is that some people may have figured out that if they %-encode their filenames on disk before upload, then they can handle non-ASCII URLs, and so they might be depending on this behavior? I guess that might be worth avoiding breakage, unless we can change `wrangler` to detect %-encoded filenames and print an error prompting the user to fix it.

I'm a little confused why the `'%not-really-percent-encoded.html'` case works at all. It seems like parsing this with Workers' broken `URL` implementation would throw an exception?

**Comment by kentonv** [comment]
I guess another way to fix this would be to update the wrangler code that generates the asset manifest to have it automatically %-encode non-ASCII characters in filenames it sees... kind of ugly though.

**Comment by EverlastingBugstopper** [comment]
>  A breaking change in a library will break them only when they update their dependency versions and re-deploy. 

Agreed - generally though we try to avoid breaking changes + if we want them we'll lump a bunch together and do a major version bump. Feels nicer that way.

**Comment by EverlastingBugstopper** [comment]
> I guess another way to fix this would be to update the wrangler code that generates the asset manifest to have it automatically %-encode non-ASCII characters in filenames it sees... kind of ugly though.

Would this fix buggy URL implementation? Or make it worse?

**Comment by harrishancock** [comment]
My main worry here is for people who change something in their site, then re-deploy, then discover their site is broken. If breaking their site like that requires first explicitly updating their dependencies, then my concern is much less (though we should at least call out the behavior change).

The '%-not-really-percent-encoded.html' case should indeed fail to parse with our implementation. I guess the unit test uses a non-buggy URL class implementation, and we shouldn't worry about that particular case?

> Would this fix buggy URL implementation? Or make it worse?

I don't think the wrangler change Kenton proposed would affect the '%-not-really...' case. I'd expect it to be broken, and remain broken, in production.

**Comment by kentonv** [comment]
> My main worry here is for people who change something in their site, then re-deploy, then discover their site is broken.

Of course, but the important question is, how likely do we think it is that people actually depend on the current behavior?

That is, do we think we have customers who have manually %-encoded their filenames on disk to work around our behavior?

For a library change, the standard of proof here is less than it would be for a runtime change.

**Comment by kentonv** [comment]
(For the record, #105 also seems like a reasonable fix.)

**Comment by EverlastingBugstopper** [comment]
yeah i think #105 is the way to go

**Comment by EverlastingBugstopper** [comment]
closed in favor of #105

**Comment by harrishancock** [comment]
> do we think we have customers who have manually %-encoded their filenames on disk to work around our behavior?

I was under the impression it's fairly common to %-encode filenames on origins (as evidenced by several of our support requests over the years), so I'm not sure people would even think of it as a workaround in a Workers Sites context. For example, if I were trying to add a space in a filename, I'm not sure I'd think twice about using %20.

That said, I could be completely wrong -- the uncertainty of my uncertainty made me flag this issue, though.

**Pull request closed without merging**
