### PR TITLE
0.0.12

### PR DESCRIPTION
**Pull request by signalnerve**

### CODE REVIEW

**Comment by SukkaW** [comment]
Will https://github.com/cloudflare/kv-asset-handler/pull/133 being included?

The current implementation of `ETag` is not perfect.

**Comment by ispivey** [comment]
We're trying to get this set of changes out today, and then get #133 reviewed and merged and release ASAP after that.

**Comment by ispivey** [comment]
FYI, the holdup here is that tests are failing, and apparently have been for a while. We're updating the configuration to make sure checks run on every PR, but we'll need to either fix the tests or ascertain that their failure isn't impactful before releasing. We're working on that now.

**Comment by SukkaW** [comment]
> FYI, the holdup here is that tests are failing

I have noticed that #146 attempts to fix the unit test.

**Comment by ispivey** [comment]
I think #147 is the most direct path to fix CI and unblock this release. I'll wait for team approvals this morning UTC-5, then we'll look to get it merged and released.

**Comment by SukkaW** [comment]
> I think #147 is the most direct path to fix CI and unblock this release. I'll wait for team approvals this morning UTC-5, then we'll look to get it merged and released.

What about utilising [`decache`](https://npm.im/decache) instead? Why revert a performance improving feature just to release a newer version?

**Comment by ispivey** [comment]
@SukkaW that should not have been merged because it fails the test suite. I don't want to cut a release when the tests are failing, because there could be legitimate failures that will impact users. There are some changes in `master` that I know people are waiting on, so I'm optimizing for getting a release out ASAP. I don't know how long it's going to take to fix the test suite, if we leave #143 in. So my choices are (a) revert and release today or (b) wait an unknown amount of time til we fix it.

If you know how to fix the test suite and want to PR it or suggest it on top of #146 I would appreciate it! That would make (b) go away 😄

**Comment by EatonZ** [comment]
@ispivey Hi, when do you expect to review and merge https://github.com/cloudflare/kv-asset-handler/pull/133?

**Pull request merged**
