### PR TITLE
Check HTTP Method after mapRequestToAsset

### LINKED ISSUE #151: Check HTTP Method after mapRequestToAsset
Currently in `getAssetFromKV` the HTTP Method is checked before the call to `mapRequestToAsset`:

https://github.com/cloudflare/kv-asset-handler/blob/3df430c248d2d8711ac69ad6497d7a32610c9e4e/src/index.ts#L96-L111

I suggest to check the HTTP method **after** this.

--- 

In my case, I want to send an e-mail on a webhook (which is a POST call from an external service - payment provider for instance).
I store my email template along my static site, so that it is uploaded to the KV store.
I want to retrieve the template using `getAssetFromKV`, (replacing the request path using `mapRequestToAsset`), however it fails because the method check is done before this.

I currently have an ugly hack, creating a new pseudo-event with a fresh GET request...

---

I don't see any drawback to moving this check after the `if` block (`mapRequestToAsset` is not supposed to have any side-effect, so calling it before failing should not be a big deal9.

I would be happy to make a PR if you think this is not a bad idea.

### PR DESCRIPTION
**Pull request by oliverpool**
Closes #151

### CODE REVIEW

**Comment by oliverpool** [comment]
@signalnerve here it is :)

**Review by Cherry — APPROVED** [review]
LGTM

**Comment by Cherry** [comment]
Waiting on Github Actions to recover (https://www.githubstatus.com/), and then I'll merge this. 👍

**Comment by signalnerve** [comment]
Ran tests locally to ensure that things work!

```
6c0dd6d ~/src/kv-asset-handler> npm test

> @cloudflare/kv-asset-handler@0.1.1 pretest /Users/kristianfreeman/src/kv-asset-handler
> npm run build


> @cloudflare/kv-asset-handler@0.1.1 build /Users/kristianfreeman/src/kv-asset-handler
> tsc -d


> @cloudflare/kv-asset-handler@0.1.1 test /Users/kristianfreeman/src/kv-asset-handler
> ava dist/test/*.js --verbose


  ✔ mapRequestToAsset › mapRequestToAsset() correctly changes /about -> /about/index.html
  ✔ mapRequestToAsset › mapRequestToAsset() correctly changes /about/ -> /about/index.html
  ✔ mapRequestToAsset › mapRequestToAsset() correctly changes /about.me/ -> /about.me/index.html
  ✔ serveSinglePageApp › serveSinglePageApp returns root asset path when request path ends in .html
  ✔ serveSinglePageApp › serveSinglePageApp returns root asset path when request path does not have extension
  ✔ serveSinglePageApp › serveSinglePageApp returns requested asset when request path has non-html extension
Environment doesnt support readable streams
Environment doesnt support readable streams
  - getAssetFromKV › getAssetFromKV when body not empty, should invoke .cancel()
  ✔ getAssetFromKV › getAssetFromKV does not cache on Cloudflare when bypass cache set
  ✔ getAssetFromKV › getAssetFromKV if not in asset manifest still returns nohash.txt
  ✔ getAssetFromKV › getAssetFromKV when setting browser caching
  ✔ getAssetFromKV › getAssetFromKV when namespace not bound fails
  ✔ getAssetFromKV › getAssetFromKV return correct val from KV and default caching
  ✔ getAssetFromKV › getAssetFromKV evaluated the file matching the extensionless path first /client/ -> client
  ✔ getAssetFromKV › getAssetFromKV evaluated the file matching the extensionless path first /client -> client
  ✔ getAssetFromKV › getAssetFromKV if no asset manifest /client -> client fails
  ✔ getAssetFromKV › getAssetFromKV if sub/ -> sub/index.html served
  ✔ getAssetFromKV › getAssetFromKV gets index.html by default for / requests
  ✔ getAssetFromKV › getAssetFromKV non ASCII path support
  ✔ getAssetFromKV › getAssetFromKV supports browser percent encoded URLs
  ✔ getAssetFromKV › getAssetFromKV supports user percent encoded URLs
  ✔ getAssetFromKV › getAssetFromKV custom key modifier
  ✔ getAssetFromKV › getAssetFromKV with no trailing slash on root
  ✔ getAssetFromKV › getAssetFromKV with no trailing slash on a subdirectory
  ✔ getAssetFromKV › getAssetFromKV no result throws an error
  ✔ getAssetFromKV › getAssetFromKV passing in a custom NAMESPACE serves correct asset
  ✔ getAssetFromKV › getAssetFromKV when setting custom cache setting
  ✔ getAssetFromKV › getAssetFromKV when custom namespace without the asset should fail
  ✔ getAssetFromKV › getAssetFromKV only decode URL when necessary
  ✔ getAssetFromKV › getAssetFromKV when etag and if-none-match are present but if-none-match !== etag, should bypass cache
  ✔ getAssetFromKV › getAssetFromKV caches on two sequential requests
  ✔ getAssetFromKV › getAssetFromKV if-none-match not sent but resource in cache, should return hit
  ✔ getAssetFromKV › getAssetFromKV if range request submitted and resource in cache, request fulfilled
  ✔ getAssetFromKV › getAssetFromKV TTls set to null should not cache on browser or edge (112ms)
  ✔ getAssetFromKV › getAssetFromKV does not store max-age on two sequential requests (118ms)
  ✔ getAssetFromKV › getAssetFromKV when if-none-match === etag and etag === pathKey in manifest, should revalidate (109ms)
Environment doesnt support readable streams
Environment doesnt support readable streams
  ─

  34 tests passed
  1 test todo
```

**Pull request merged**
